// maneuver.ks executes the next maneuver node
@lazyGlobal off.

print "RUNNING maneuver".

// import libraries
runOncePath("0:/src/core/engine").
runOncePath("0:/src/core/burn").

local nd is nextNode.

// calculate estimate of burn duration
local pressure is 0.
local flowRate is availableMassFlowRateAt(pressure).

print "current max flow rate: " + availableMassFlowRate().
print "vacuum max flow rate: " + flowRate.

local effectiveExhaustVelocity is ship:availableThrustAt(pressure)/flowRate. // isp in n*s/kg = ev in m/s
local burnDuration is burnTime(ship:mass, nd:deltav:mag-1, effectiveExhaustVelocity, flowRate).

local nextMass1 is rocketEquationFinalMass(ship:mass, nd:deltav:mag-1, effectiveExhaustVelocity).
local flowRate1 is nextMass1/effectiveExhaustVelocity.
set burnDuration to burnDuration + burnTime(nextMass1, 0.9, effectiveExhaustVelocity, flowRate1).

local nextMass2 to rocketEquationFinalMass(nextMass1, 0.9, effectiveExhaustVelocity).
local flowRate2 is 0.1*flowRate1.
set burnDuration to burnDuration + burnTime(nextMass2, 0.1, effectiveExhaustVelocity, flowRate2).

local flowRateSum is flowRate + flowRate1 + flowRate2.
local burnStart is (flowRate/flowRateSum)*meanBurnTime(ship:mass, nd:deltav:mag-1, effectiveExhaustVelocity, flowRate).
set burnStart to burnStart + (flowRate1/flowRateSum)*meanBurnTime(nextMass1, 0.9, effectiveExhaustVelocity, flowRate1).
set burnStart to burnStart + (flowRate2/flowRateSum)*meanBurnTime(nextMass2, 0.1, effectiveExhaustVelocity, flowRate2).

print("Estimated burn duration of " + round(burnDuration, 3) + " seconds").
print("Crude Estimate: " + round(nd:deltav:mag/(ship:availablethrust/ship:mass), 3) + " seconds").
print("Starting burn " + round(burnStart, 3) + " seconds before node ETA").

// load rocket state
local rocketState is lexicon().
set rocketState to readJson("state.json").

// create key execute_maneuver if none exists
if not rocketState:hassuffix("execute_maneuver") {
    rocketState:add("execute_maneuver", false).
}

// add a Kerbal Alarm Clock alarm to kick simulation out of warp a minute before the burn should start.
if addons:available("KAC") and rocketState["execute_maneuver"] = false {
    addAlarm("Maneuver", time:seconds + nd:eta - (burnStart + 60), "Maneuver Node", "Auto-Generated by kOS script").
}

// set execute_maneuver to true
set rocketState["execute_maneuver"] to true.

// save rocket state now that we've changed it
writeJson(rocketState, "state.json").

// wait until 60 seconds before burn
wait until nd:eta <= burnStart + 60.

// turn to face the direction the rocket's velocity is changing in
local dv0 is nd:deltaV.
sas off.
lock steering to dv0.

// wait until rocket is facing the right direction
wait until vang(dv0, ship:facing:vector) < 0.25.

// wait until burn start
wait until nd:eta <= burnStart + 10.
kuniverse:timewarp:cancelwarp().
wait until kuniverse:timewarp:isSettled().
wait until nd:eta <= burnStart.

// set execute_maneuver to false
set rocketState["execute_maneuver"] to false.
writeJson(rocketState, "state.json").

// create a setpoint we can manipulate
local throttleSetpoint is 0.
lock throttle to throttleSetpoint.

// execute maneuver node
local burnStop is burnDuration-burnStart.
lock steering to nd:deltav.
set throttleSetpoint to 1.

wait until nd:deltaV:mag < 1 or nd:eta <= -burnStop or vDot(dv0, nd:deltav) < 0.
set throttleSetpoint to 1*ship:mass/ship:availableThrustAt(pressure).

wait until nd:deltaV:mag < 0.1 or nd:eta <= -burnStop or vDot(dv0, nd:deltav) < 0.
set throttleSetpoint to 0.1*ship:mass/ship:availableThrustAt(pressure).

wait until nd:deltaV:mag < 0.01 or nd:eta <= -burnStop or vDot(dv0, nd:deltav) < 0.
set throttleSetpoint to 0.

// print stats
print "End burn, remain dv " + round(nd:deltav:mag,1) + "m/s, vdot: " + round(vdot(dv0, nd:deltav),1).

// remove node so we can execute future ones
remove nd.

// unlock controls
unlock steering.
unlock throttle.

// sets user's throttle setting to zero to prevent throttle from
// returning to the throttle value it was before it was run
set ship:control:pilotMainThrottle to 0.

// unlock steering and turn on stability assist
unlock steering.
sas on.
